Repository jaychenblue/scout-concordia, pull requests merged in 2020-04, with the labels that each got.

#235 Adding nodes
  app/src/debug/res/raw/encryptedhall1nodes
  app/src/debug/res/raw/encryptedhall2nodes
  app/src/debug/res/raw/filestoencrypt
  app/src/debug/res/raw/hall1nodes
  app/src/debug/res/raw/hall1nodes2
  app/src/debug/res/raw/hall2nodes
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/res/layout/activity_maps.xml
Labels: enhancement

#239 Directions to a schedule event
  app/src/main/java/com/example/scoutconcordia/Activities/CalendarActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
Labels: enhancement

#240 Defect fixes for D-14, D-15, D-16
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
Labels: Quality metrics, Refactoring

#263 Defect fixes for D-17 and D-18
  app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
Labels: Quality metrics, Refactoring

#267 Bug fix directions
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
Labels: bug

#268 [#258] Added JavaDoc comments to the ShuttleInfo class
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
Labels: Quality metrics, Refactoring, documentation

#278 Adding Refactored ShuttleInfo class into master
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
Labels: Quality metrics, Refactoring, enhancement

#290 Fix for the app crash on map click immediately after application launch
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
Labels: bug

#296 modify the comments to make it more informative
  app/src/main/java/com/example/scoutconcordia/Activities/CalendarActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/ShuttleScheduleActivity.java
Labels: documentation
