Repository jaychenblue/scout-concordia, pull requests merged in 2020-03, with the labels that each got.

#169 Refactoring JUnit tests
  app/build.gradle
  app/src/test/java/com/example/scoutconcordia/BuildingInfoTest.java
  app/src/test/java/com/example/scoutconcordia/LinkedListTest.java
Labels: Refactoring, Testing

#165 Importing and displaying the user's Google Calendar on the app.
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/scoutconcordia/CalendarActivity.java
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature

#174 Fix building outline bug
  app/src/main/java/com/example/scoutconcordia/MapsActivity.java
Labels: bug

#179 Refactoring classes into packages
  app/src/androidTest/java/com/example/scoutconcordia/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/example/scoutconcordia/SwitchCampus.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/scoutconcordia/Activities/CalendarActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/MainActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/ShuttleScheduleActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/SplashScreenActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/BuildingInfo.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/CustomInfoWindow.java
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_shuttle_schedule.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/test/java/com/example/scoutconcordia/BuildingInfoTest.java
  app/src/test/java/com/example/scoutconcordia/LinkedListTest.java
Labels: Refactoring

#171 [#139] Importable nodes
  app/src/debug/res/raw/downtownlocations2.txt
  app/src/debug/res/raw/filestoencrypt
  app/src/debug/res/raw/hall8nodes.txt
  app/src/debug/res/raw/testfile.txt
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/BuildingInfo.java
Labels: enhancement

#184 Creation of Shortest Path
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/N_aryTree.java
Labels: enhancement

#188 Refactor file access
  app/src/debug/res/raw/encrypteddtown
  app/src/debug/res/raw/encryptedloyola
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/FileAccessor.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/BuildingInfo.java
Labels: Refactoring

#162 shuttle-estimate
  app/src/debug/res/raw/schedule_friday_loyola.txt
  app/src/debug/res/raw/schedule_friday_sgw.txt
  app/src/debug/res/raw/schedule_montothurs_loyola.txt
  app/src/debug/res/raw/schedule_montothurs_sgw.txt
  app/src/main/java/com/example/scoutconcordia/Activities/MainActivity.java
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
  settings.gradle
Labels: Refactoring, enhancement

#187 UI for Google directions to a building
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/res/color/travel_mode_bar_button_selector.xml
  app/src/main/res/drawable/ic_directions_black_24dp.xml
  app/src/main/res/drawable/ic_directions_car_black_24dp.xml
  app/src/main/res/drawable/ic_directions_transit_black_24dp.xml
  app/src/main/res/drawable/ic_directions_walk_black_24dp.xml
  app/src/main/res/drawable/ic_location_on_black_24dp.xml
  app/src/main/res/drawable/ic_my_location_black_24dp.xml
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/outdoor_buildings_diections_ui.xml
  app/src/main/res/menu/travel_modes_bar.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: UI

#189 Decipher adjacent nodes
  app/build.gradle
  app/src/debug/res/raw/encryptedhall8nodes
  app/src/debug/res/raw/hall8nodes
  app/src/debug/res/raw/hall8nodes.txt
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/res/drawable-v24/bluesquare.jpg
  app/src/main/res/drawable-v24/hall2p.png
  app/src/main/res/drawable-xxhdpi/hall8p.png
  app/src/main/res/drawable-xxhdpi/hall9p.png
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/values/refs.xml
Labels: enhancement

#192 Outdoor directions to concordia buildings
  app/build.gradle
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/res/color/travel_mode_bar_button_selector.xml
  app/src/main/res/layout/outdoor_buildings_diections_ui.xml
  app/src/main/res/menu/travel_modes_bar.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#193 Indoor outdoor directions
  app/src/debug/res/raw/cc1nodes
  app/src/debug/res/raw/cc2nodes
  app/src/debug/res/raw/encryptedcc1nodes
  app/src/debug/res/raw/encryptedcc2nodes
  app/src/debug/res/raw/encryptedhall1nodes
  app/src/debug/res/raw/encryptedhall8nodes
  app/src/debug/res/raw/encryptedhall9nodes
  app/src/debug/res/raw/filestoencrypt
  app/src/debug/res/raw/hall1nodes
  app/src/debug/res/raw/hall1nodes2
  app/src/debug/res/raw/hall2nodes
  app/src/debug/res/raw/hall8nodes
  app/src/debug/res/raw/hall9nodes
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/BuildingInfo.java
  app/src/main/res/drawable-mdpi/cc_building1.png
  app/src/main/res/drawable-mdpi/hall2floor.png
  app/src/main/res/drawable-v24/hall1p.png
  app/src/main/res/drawable/cc_building2.png
  app/src/main/res/layout/activity_maps.xml
Labels: Feature

#194 Unit tests for sprint 3
  app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
  app/src/main/java/com/example/scoutconcordia/DataStructures/N_aryTree.java
  app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
  app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
  app/src/test/java/com/example/scoutconcordia/FileAccessorTest.java
  app/src/test/java/com/example/scoutconcordia/GraphTest.java
  app/src/test/java/com/example/scoutconcordia/LinkedListTest.java
  app/src/test/java/com/example/scoutconcordia/N_aryTreeTest.java
  app/src/test/java/com/example/scoutconcordia/ShuttleInfoTest.java
Labels: Testing

#195 Automated system tests
  app/src/androidTest/java/com/example/scoutconcordia/MapTest.java
  app/src/androidTest/java/com/example/scoutconcordia/SwitchCampus.java
Labels: Testing
